#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"
APP_DIR="$ROOT_DIR/apps/dioxus-app"

FEATURES="${DX_FEATURES:-wfst-decoder,fetch-data}"
OUT_DIR="${WEB_DIST_DIR:-dist/web-release}"
SESSION_CACHE_DIR="${DX_SESSION_CACHE_DIR:-/tmp/dx-session-cache}"
HEAD_SNIPPET="$ROOT_DIR/assets/web_preboot_head.html"
BODY_SNIPPET="$ROOT_DIR/assets/web_preboot_body.html"
BASE_PATH_INPUT="${KHMERIME_BASE_PATH:-${WEB_BASE_PATH:-}}"
BUILD_DIR="$ROOT_DIR/target/dx/roman_lookup/release/web/public"
BUILD_ASSETS_DIR="$BUILD_DIR/assets"

normalize_base_path() {
  local raw="$1"
  # Accept either "/foo/bar" or "foo/bar", and normalize to "foo/bar".
  if [[ "$raw" == "." || "$raw" == "./" ]]; then
    printf ""
    return 0
  fi
  raw="${raw#/}"
  raw="${raw%/}"
  if [[ "$raw" == "." ]]; then
    raw=""
  fi
  printf "%s" "$raw"
}

BASE_PATH="$(normalize_base_path "$BASE_PATH_INPUT")"
# Keep a single source of truth for the Rust runtime helper too.
if [[ -n "$BASE_PATH" ]]; then
  export KHMERIME_BASE_PATH="/$BASE_PATH"
else
  unset KHMERIME_BASE_PATH || true
fi

mkdir -p "$SESSION_CACHE_DIR"

inject_shell_splash() {
  local index_html="$1"
  if [[ ! -f "$index_html" ]] || grep -q 'id="app-preboot-splash"' "$index_html"; then
    return 0
  fi

  local original_mode="644"
  local mode_probe
  if mode_probe="$(stat -c '%a' "$index_html" 2>/dev/null)"; then
    original_mode="$mode_probe"
  fi

  local tmp_file
  tmp_file="$(mktemp)"
  awk -v head_snippet="$HEAD_SNIPPET" -v body_snippet="$BODY_SNIPPET" '
    /<\/head>/ && !inserted_head {
      while ((getline line < head_snippet) > 0) {
        print line
      }
      close(head_snippet)
      inserted_head = 1
    }
    /<div id="main"><\/div>/ && !inserted_body {
      while ((getline line < body_snippet) > 0) {
        print line
      }
      close(body_snippet)
      inserted_body = 1
    }
    { print }
  ' "$index_html" > "$tmp_file"
  mv "$tmp_file" "$index_html"
  chmod "$original_mode" "$index_html" 2>/dev/null || chmod 0644 "$index_html"
}

sanitize_index_asset_paths() {
  local index_html="$1"
  if [[ ! -f "$index_html" ]]; then
    return 0
  fi
  # Some Dioxus builds emit "/./assets/..." when no explicit base path is set.
  # Normalize this to "/assets/..." to avoid brittle hosting behavior.
  sed -i 's|/\./assets/|/assets/|g' "$index_html"
}

# Require a real wasm-opt in release builds.
WASM_OPT_BIN="${WASM_OPT_BIN:-wasm-opt}"
WASM_OPT_REQUIRED="${WASM_OPT_REQUIRED:-1}"

if [[ "$WASM_OPT_REQUIRED" == "1" ]]; then
  if ! command -v "$WASM_OPT_BIN" >/dev/null 2>&1; then
    echo "ERROR: wasm-opt is required for web release builds but was not found." >&2
    echo "Install Binaryen (provides wasm-opt), or set WASM_OPT_REQUIRED=0 to bypass locally." >&2
    exit 1
  fi
fi

DX_CMD=(dx build --platform web --release --session-cache-dir "$SESSION_CACHE_DIR")
if [[ -n "$FEATURES" ]]; then
  DX_CMD+=(--features "$FEATURES")
fi
if [[ -n "$BASE_PATH" ]]; then
  DX_CMD+=(--base-path "$BASE_PATH")
fi

# Avoid accumulating stale content-hashed runtime files across repeated builds.
if [[ -d "$BUILD_ASSETS_DIR" ]]; then
  find "$BUILD_ASSETS_DIR" -maxdepth 1 -type f \
    \( -name 'roman_lookup-*.js' -o -name 'roman_lookup_bg-*.wasm' \) -delete
fi

echo "Building web release bundle..."
if [[ -n "${KHMERIME_BASE_PATH:-}" ]]; then
  echo "Using base path: $KHMERIME_BASE_PATH"
fi
(
  cd "$APP_DIR"
  "${DX_CMD[@]}"
)

if [[ ! -d "$BUILD_DIR" ]]; then
  echo "Expected build output missing: $BUILD_DIR" >&2
  exit 1
fi

if [[ ! -f "$BUILD_DIR/index.html" ]]; then
  echo "Expected release index missing from $BUILD_DIR" >&2
  exit 1
fi

if ! find "$BUILD_ASSETS_DIR" -maxdepth 1 -type f \( -name 'roman_lookup-*.js' -o -name 'roman_lookup_bg-*.wasm' \) | grep -q .; then
  echo "Expected web runtime artifacts missing from $BUILD_DIR" >&2
  exit 1
fi

# Copy lazy-loaded data blobs generated by build.rs into the served assets directory.
if [[ -d "$ROOT_DIR/assets/data" ]]; then
  rm -rf "$BUILD_ASSETS_DIR/data"
  cp -R "$ROOT_DIR/assets/data" "$BUILD_ASSETS_DIR/data"
fi

# Copy main.css and other static assets.
if [[ -f "$ROOT_DIR/assets/main.css" ]]; then
  cp "$ROOT_DIR/assets/main.css" "$BUILD_ASSETS_DIR/main.css"
fi
if [[ -d "$ROOT_DIR/assets/css" ]]; then
  rm -rf "$BUILD_ASSETS_DIR/css"
  cp -R "$ROOT_DIR/assets/css" "$BUILD_ASSETS_DIR/css"
fi
if [[ -d "$ROOT_DIR/assets/vendor" ]]; then
  rm -rf "$BUILD_ASSETS_DIR/vendor"
  cp -R "$ROOT_DIR/assets/vendor" "$BUILD_ASSETS_DIR/vendor"
fi

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
cp -R "$BUILD_DIR"/. "$OUT_DIR"/
inject_shell_splash "$OUT_DIR/index.html"
sanitize_index_asset_paths "$OUT_DIR/index.html"
echo "Deployable web bundle written to: $OUT_DIR"
