[application]
name = "roman_lookup"
out_dir = "../../dist"
asset_dir = "../../assets"

[web.app]
title = "Roman Lookup IME"

[web.watcher]
watch_path = ["src", "../../assets", "../../data", "../../config"]
